spatial_cv: False
subject: "fsaverage"
data_path: "bsi_zoo/tests/data/"
memory_path: "."
n_jobs: 30
nruns: 1
random_state: 42

estimator: "gamma_map"
estimator_args:
  alpha: 0.5 # regularization parameter
estimator_extra_params:
  update_mode: 2
  max_iter: 1000
  tol: 1e-15
  gammas: # gamma initialization
    fixed: 
      enabled: true
      value: 0.001 # small positive number
    random_uniform:
      enabled: false
      low: 0.001
      high: 0.1
    ones: # (for compatibility with MNE)
      enabled: true
      value: 1.0

data_args_II:
    orientation_type: "fixed"
    cov_type: "full"
    alpha_SNR: 0.99
    nnz: 5
    n_times: 2

metrics:
    - emd